
server:
  port: 7071
  servlet:
    context-path: /



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fullstackdevelopment?allowMultiQueries=true&serverTimezone=GMT-8
    username: root
    password: 123456
    driver-class-name:  com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

projectHttp: "Http://localhost:7071"

#如果数据为空的字段，则该字段省略不显示，可以通过添加配置文件，规定查询数据为空是则返回null。
mybatis:
  configuration:
    call-setters-on-nulls: true







